#!/bin/bash
set -o errexit -o pipefail -o noclobber -o nounset 				#Common safety settings, useful for most scripts.

help='Creates one or multiple new bash script(s) with a small template, makes it executable by the current user and opens it for editing..

Usage:
    create-script SCRIPT_NAME... [options]
    create-script -h/--help
Arguments:
    FILE_NAME...     One or more a_filenames for the scripts.
Options:
    -h/--help      Show this help dialog.
    -b/--blank     Skips the usual template.
    -e/--editor    Open the script in $EDITOR afterwards.'

#============================ Safe Guards ==============================
#Valid Argument Counts
min_args=1
max_args=-1				#Set to -1 for scripts that take unlimited args.

#Exit Codes
EXIT_SUCCESS=0
EXIT_TOO_FEW_ARGS=10
EXIT_TOO_MANY_ARGS=11

EXIT_MISSING_SCRIPT_PATH_ENV_VAR=1

if [ -z "$CUSTOM_SCRIPTS_PATH" ]; then
	echo "[ERROR] \$CUSTOM_SCRIPTS_PATH not set. Set it to some dir then run this script."
	exit $EXIT_MISSING_SCRIPT_PATH_ENV_VAR
fi

if [ $# -lt $min_args ]; then
	echo "[ERROR] Requires at least one filename. Use -h for help."
	exit $EXIT_TOO_FEW_ARGS
fi

if [ $max_args -ne -1 ] && [ $# -gt $max_args ]; then
	echo "[ERROR] Too many arguments. Use -h for help."
	exit $EXIT_TOO_MANY_ARGS
fi


#============================ Script Vars ==============================
#Options
o_help=false
o_blank=false
o_editor=false

#Arguments
a_filenames=()

for arg; do
	if   [ "$arg" == "-h" ] || [ "$arg" == "--help" ];     then o_help=true
	elif [ "$arg" == "-b" ] || [ "$arg" == "--blank" ];    then o_blank=true 
	elif [ "$arg" == "-e" ] || [ "$arg" == "--editor" ]; then o_editor=true
	else a_filenames+=("$arg"); fi
done
# echo $o_help  $o_blank $o_editor
# echo "${a_filenames[*]}"

template='#!/bin/bash
set -o errexit -o pipefail -o noclobber -o nounset 				#Common safety settings, useful for most scripts.

help='"'"'DESCRIPTION

Usage:
    {SCRIPT_NAME} REQ_ARG_1 [options]
    {SCRIPT_NAME} -h/--help
Arguments:
    REQ_ARG_1    DESCRIPTION.
Options:
    -h/--help    Show this help dialog.'"'"'

#============================ Safe Guards ==============================
#Valid Argument Counts
min_args=1
max_args=-1				#Set to -1 for scripts that take unlimited args.

#Exit Codes
EXIT_SUCCESS=0
EXIT_TOO_FEW_ARGS=10
EXIT_TOO_MANY_ARGS=11

if [ $# -lt $min_args ]; then
	echo "[ERROR] Not enough arguments. Use -h for help."
	exit $EXIT_TOO_FEW_ARGS
fi

if [ $max_args -ne -1 ] && [ $# -gt $max_args ]; then
	echo "[ERROR] Too many arguments. Use -h for help."
	exit $EXIT_TOO_MANY_ARGS
fi

#============================ Script Vars ==============================
#Options
o_help=false

#Arguments

for arg; do
	if   [ "$arg" == "-h" ] || [ "$arg" == "--help" ]; then o_help=true
	fi
done

#============================ Main ==============================
if $o_help; then
	echo "$help"
	exit $EXIT_SUCCESS
fi

exit $EXIT_SUCCESS'

#============================ Main ==============================
if $o_help; then
	echo "$help"
	exit $EXIT_SUCCESS
fi

if ! [ -d "$CUSTOM_SCRIPTS_PATH" ]; then
	echo "\$CUSTOM_SCRIPTS_PATH does not exist, creating it."
	mkdir "$CUSTOM_SCRIPTS_PATH"
fi

for filename in "$a_filenames"; do
	target="$CUSTOM_SCRIPTS_PATH/$filename"
	echo "Creating $target and chmod-ing it."

	if $o_blank; then
		echo "Making blank file."
		touch "$target"
	else
		echo "Adding the usual template to it."
		echo "${template//\{SCRIPT_NAME\}/$filename}" > "$target"
	fi
	chmod +x "$target"
done

if $o_editor; then
	$EDITOR "${a_filenames[@]}"
fi

exit $EXIT_SUCCESS
