#!/bin/bash
set -o errexit -o pipefail -o noclobber -o nounset 				#Common safety settings, useful for most scripts.

help='Gets an X11-window-ID for a specific window, using the program'"'"'s name.

Usage:
    get-x11-window-id-from-program-name PROGRAM_NAME
    get-x11-window-id-from-program-name -h/--help
Options:
    -h/--help    Show this help dialog.'

#============================ Safe Guards ==============================
#Valid Argument Counts
min_args=0
max_args=1				#Set to -1 for scripts that take unlimited args.

#Exit Codes
EXIT_SUCCESS=0
EXIT_TOO_FEW_ARGS=10
EXIT_TOO_MANY_ARGS=11

if [ $# -lt $min_args ]; then
	echo "[ERROR] Not enough arguments. Use -h for help."
	exit $EXIT_TOO_FEW_ARGS
fi

if [ $max_args -ne -1 ] && [ $# -gt $max_args ]; then
	echo "[ERROR] Too many arguments. Use -h for help."
	exit $EXIT_TOO_MANY_ARGS
fi

#============================ Script Vars ==============================
#Options
o_help=false

for arg; do
	if [ "$arg" == "-h" ] || [ "$arg" == "--help" ]; then o_help=true
	fi
done

#============================ Main ==============================
if $o_help; then
	echo "$help"
	exit $EXIT_SUCCESS
fi

window_id=$(wmctrl -l | grep "$1" | cut -d ' ' -f 1)

echo $window_id
#return $window_id

exit $EXIT_SUCCESS
