#!/bin/bash
set -o errexit -o pipefail -o noclobber -o nounset 				#Common safety settings, useful for most scripts.

help='Brings up a notification showing the current time, date, and Unix time. I mainly made this because I disabled my taskbar.
Usage:
    popup-date-time-notification
    popup-date-time-notification -h/--help
Options:
    -h/--help                Show this help dialog.
       --unicode-table       Draw the surronding table with round edges.
       --round-table         Draw the surronding table using Unicode box-drawing characters, instead of standard ASCII characters.
    -t/--expire-time=TIME    [Not Yet Implemented!] Passed to notify-send. The duration, in ms, to stay on screen. Overrides the user'"'"'s default.
    -e/--transient           Passed to notify-send. Persist until the user acknowledges it. Overrides the user'"'"'s default.'

#============================ Config ==============================
app_name="Actives Time Popup"

#============================ Safe Guards ==============================
#Valid Argument Counts
min_args=0
max_args=4				#Set to -1 for scripts that take unlimited args.

#Exit Codes
EXIT_SUCCESS=0
EXIT_TOO_FEW_ARGS=10
EXIT_TOO_MANY_ARGS=11

if [ $# -lt $min_args ]; then
	echo "[ERROR] Not enough arguments. Use -h for help."
	exit $EXIT_TOO_FEW_ARGS
fi

if [ $max_args -ne -1 ] && [ $# -gt $max_args ]; then
	echo "[ERROR] Too many arguments. Use -h for help."
	exit $EXIT_TOO_MANY_ARGS
fi

#============================ Script Vars ==============================
#Options
o_help=false
o_unicode_table=false
o_round_table=false
o_expire_time=false 	#FIXME: -t/--expire-time is not yet implemented.
o_transient=false

#Arguments

for arg; do
	if   [ "$arg" == "-h" ] || [ "$arg" == "--help" ];        then o_help=true
	elif [ "$arg" == "--unicode-table" ];                     then o_unicode_table=true
	elif [ "$arg" == "--round-table" ];                       then o_round_table=true
	elif [ "$arg" == "-t" ] || [ "$arg" == "--expire-time" ]; then o_expire_time=true
	elif [ "$arg" == "-e" ] || [ "$arg" == "--transient" ];   then o_transient=true
	fi
done

#============================ Templates ==============================
ascii="\
+------------+---+
| 1765883218 | U |
+------------+---+
| 2025-12-16 | D |
| 51  ~  Tue | W |
+------------+---+
|  14:06:58  | T |
+------------+---+"

ascii_round="\
/------------+---\\
| 1765883218 | U |
+------------+---+
| 2025-12-16 | D |
| 51  ~  Tue | W |
+------------+---+
|  14:06:58  | T |
\\------------+---/"

unicode="\
┌────────────┬───┐
│ 1765883218 │ U │
├────────────┼───┤
│ 2025-12-16 │ D │
│ 51  ~  Tue │ W │
├────────────┼───┤
│  14:06:58  │ T │
└────────────┴───┘"

unicode_round="\
╭────────────┬───╮
│ %s │ U │
├────────────┼───┤
│ %s │ D │
│ %s │ W │
├────────────┼───┤
│  %s  │ T │
╰────────────┴───╯"

#============================ Main ==============================
if $o_help; then
	echo "$help"
	exit $EXIT_SUCCESS
fi

#Figure out which template to use.
if $o_unicode_table; then
	$o_round_table && msg_template="$unicode_round" || msg_template="$unicode"
else
	$o_round_table && msg_template="$ascii_round"   || msg_template="$ascii"
fi

#Get current date/time information.
unix=$(date "+%s")
date=$(date "+%F")
week=$(date "+%V  ~  %a")
time=$(date "+%H:%M:%S")

#Format the message accordingly.
printf -v msg -- "$msg_template" "$unix" "$date" "$week" "$time"

#Send it out to the user.
echo "$msg"
notify-send -u low -a "$app_name" "$msg"

exit $EXIT_SUCCESS
