#!/bin/bash
result=${PWD##*/}          # to assign to a variable
echo $result
result=${result:-/}        # to correct for the case where PWD=/
echo $result

printf '%s\n' "${PWD##*/}" # to print to stdout
                           # ...more robust than echo for unusual names
                           #    (consider a directory named -e or -n)

printf '%q\n' "${PWD##*/}" # to print to stdout, quoted for use as shell input
                           # ...useful to make hidden characters readable.
